[project]
name = "cleansweep"
version = "0.0.1"
description = "CleanSweep - variant calling with plate swipe data"

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]