name: cleansweep-ci
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - bcftools>=1.18
  - htslib
  - pysam
  - numpy
  - scipy
  - pandas
  - joblib
  - biopython
  - matplotlib=3.10
  - pymc=5.12.0
  - arviz=0.21.0
  - pytensor
  - pytest
  - pytest-timeout
  - scikit-learn
