"""Integration tests for `cleansweep prepare` CLI.

All inputs are generated by session-scoped fixtures in conftest.py; outputs
are written to pytest's tmp_path so no pre-existing directories are required.
"""
import shutil
import subprocess

import pytest

pytestmark = pytest.mark.skipif(
    shutil.which("nucmer") is None,
    reason="nucmer not available in this environment",
)


class TestCleanSweepPrepareCLI:

    def test_no_background_option(self, synthetic_target_fasta, tmp_path):
        """Prepare with no --background argument (background defaults to None)."""
        cmd = [
            "cleansweep", "prepare",
            str(synthetic_target_fasta),
            "-o", str(tmp_path / "out"),
            "-V", "4", "-mi", "0.95",
        ]
        rc = subprocess.run(cmd, capture_output=True)
        assert rc.returncode == 0, rc.stderr.decode()

    def test_no_background_strain(self, synthetic_target_fasta, tmp_path):
        """Prepare with --background but no files supplied (empty list)."""
        cmd = [
            "cleansweep", "prepare",
            str(synthetic_target_fasta),
            "--background",
            "-o", str(tmp_path / "out"),
            "-V", "4", "-mi", "0.95",
        ]
        rc = subprocess.run(cmd, capture_output=True)
        assert rc.returncode == 0, rc.stderr.decode()

    def test_with_background_fastas(
        self, synthetic_target_fasta, synthetic_background_fastas, tmp_path
    ):
        """Prepare with two background FASTA files."""
        cmd = [
            "cleansweep", "prepare",
            str(synthetic_target_fasta),
            "--background", *[str(f) for f in synthetic_background_fastas],
            "-o", str(tmp_path / "out"),
            "-V", "4", "-mi", "0.95", "-k",
        ]
        rc = subprocess.run(cmd, capture_output=True)
        assert rc.returncode == 0, rc.stderr.decode()

    def test_with_background_fastas_gzip(
        self, synthetic_target_fasta_gz, synthetic_background_fastas_gz, tmp_path
    ):
        """Prepare accepts gzip-compressed FASTA inputs."""
        cmd = [
            "cleansweep", "prepare",
            str(synthetic_target_fasta_gz),
            "--background", *[str(f) for f in synthetic_background_fastas_gz],
            "-o", str(tmp_path / "out"),
            "-V", "4", "-mi", "0.95", "-k",
        ]
        rc = subprocess.run(cmd, capture_output=True)
        assert rc.returncode == 0, rc.stderr.decode()

    def test_creates_reference_fasta(
        self, synthetic_target_fasta, synthetic_background_fastas, tmp_path
    ):
        """Prepare creates cleansweep.reference.fa in the output directory."""
        outdir = tmp_path / "out"
        cmd = [
            "cleansweep", "prepare",
            str(synthetic_target_fasta),
            "--background", *[str(f) for f in synthetic_background_fastas],
            "-o", str(outdir),
            "-V", "4", "-mi", "0.95",
        ]
        subprocess.run(cmd, capture_output=True, check=True)
        assert (outdir / "cleansweep.reference.fa").exists()

    def test_creates_swp_file(
        self, synthetic_target_fasta, synthetic_background_fastas, tmp_path
    ):
        """Prepare creates cleansweep.prepare.swp in the output directory."""
        outdir = tmp_path / "out"
        cmd = [
            "cleansweep", "prepare",
            str(synthetic_target_fasta),
            "--background", *[str(f) for f in synthetic_background_fastas],
            "-o", str(outdir),
            "-V", "4", "-mi", "0.95",
        ]
        subprocess.run(cmd, capture_output=True, check=True)
        assert (outdir / "cleansweep.prepare.swp").exists()
