[package]
name = "mcmc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "mcmc"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.25.0"
rand = "0.9.1"
rand_distr = "0.5.1"
statrs = "0.18.0"
